#@Template

[Product]

ProductType = "Graph"
TotalWidth = "1000"
TotalHeight = "500"
MainTitleString = "Surface Water Supply Index (SWSI)"
SubTitleString = "4 = extremely wet, -4 = extremely dry"
VisibleStart = ${VisibleStart}
VisibleEnd = ${VisibleEnd}

[SubProduct 1]

GraphType = "Raster"
LeftYAxisLegendPosition = "Left"
LegendFormat = "%L"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""
SymbolTablePath = "${WorkingDir}/71-Create-SWSI-HeatMap-symtable.csv"

[Data 1.1]

TSID = "HUC:14010001.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14010001-TimeSeries.dv"
TSAlias = "HUC:14010001-DataComposite-SWSI"

[Data 1.2]

TSID = "HUC:14010002.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14010002-TimeSeries.dv"
TSAlias = "HUC:14010002-DataComposite-SWSI"

[Data 1.3]

TSID = "HUC:14010003.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14010003-TimeSeries.dv"
TSAlias = "HUC:14010003-DataComposite-SWSI"

[Data 1.4]

TSID = "HUC:14010004.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14010004-TimeSeries.dv"
TSAlias = "HUC:14010004-DataComposite-SWSI"

[Data 1.5]

TSID = "HUC:14010005.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14010005-TimeSeries.dv"
TSAlias = "HUC:14010005-DataComposite-SWSI"

[Data 1.6]

TSID = "HUC:14020001.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14020001-TimeSeries.dv"
TSAlias = "HUC:14020001-DataComposite-SWSI"

[Data 1.7]

TSID = "HUC:14020002.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14020002-TimeSeries.dv"
TSAlias = "HUC:14020002-DataComposite-SWSI"

[Data 1.8]

TSID = "HUC:14020003.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14020003-TimeSeries.dv"
TSAlias = "HUC:14020003-DataComposite-SWSI"

[Data 1.9]

TSID = "HUC:14020004.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14020004-TimeSeries.dv"
TSAlias = "HUC:14020004-DataComposite-SWSI"

[Data 1.10]

TSID = "HUC:14020005.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14020005-TimeSeries.dv"
TSAlias = "HUC:14020005-DataComposite-SWSI"

[Data 1.11]

TSID = "HUC:14020006.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14020006-TimeSeries.dv"
TSAlias = "HUC:14020006-DataComposite-SWSI"

[Data 1.12]

TSID = "HUC:14030003.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14030003-TimeSeries.dv"
TSAlias = "HUC:14030003-DataComposite-SWSI"

[Data 1.13]

TSID = "HUC:14030002.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14030002-TimeSeries.dv"
TSAlias = "HUC:14030002-DataComposite-SWSI"

[Data 1.14]

TSID = "HUC:14080101.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14080101-TimeSeries.dv"
TSAlias = "HUC:14080101-DataComposite-SWSI"

[Data 1.15]

TSID = "HUC:14080102.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14080102-TimeSeries.dv"
TSAlias = "HUC:14080102-DataComposite-SWSI"

[Data 1.16]

TSID = "HUC:14080104.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14080104-TimeSeries.dv"
TSAlias = "HUC:14080104-DataComposite-SWSI"

[Data 1.17]

TSID = "HUC:14080105.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14080105-TimeSeries.dv"
TSAlias = "HUC:14080105-DataComposite-SWSI"

[Data 1.18]

TSID = "HUC:14080107.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14080107-TimeSeries.dv"
TSAlias = "HUC:14080107-DataComposite-SWSI"

[Data 1.19]

TSID = "HUC:14050001.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14050001-TimeSeries.dv"
TSAlias = "HUC:14050001-DataComposite-SWSI"

[Data 1.20]

TSID = "HUC:14050002.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14050002-TimeSeries.dv"
TSAlias = "HUC:14050002-DataComposite-SWSI"

[Data 1.21]

TSID = "HUC:14050003.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14050003-TimeSeries.dv"
TSAlias = "HUC:14050003-DataComposite-SWSI"

[Data 1.22]

TSID = "HUC:14050005.CALC.DataComposite-SWSI.Month~DateValue~D:\Users\steve\projects\babbitt-indicators\swsi\2023-01\Results-Web/ts/14050005-TimeSeries.dv"
TSAlias = "HUC:14050005-DataComposite-SWSI"
