# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Open Water Foundation / Surface Water Supply Index 
nav:
- Home: index.md
- Introduction: introduction/introduction.md
- Colorado SWSI Methodology: co-methodology/co-methodology.md
- Colorado SWSI Output Products: co-output/co-output.md
- Colorado SWSI Folders: co-folders/co-folders.md
- Colorado SWSI Procedure: co-procedure/co-procedure.md
- References: references/references.md
- 'Appendix - Definitions': appendix-definitions/definitions.md
- 'Appendix - TSTool Command Summary': appendix-tstool-commands/tstool-commands.md
- 'Appendix - Release Notes': appendix-release-notes/release-notes.md
- 'Appendix A - NRCS Native Flow Equations': appendix-a/nrcs-native-flow-equations.md
- 'Appendix B - Station Assignments by HUC': appendix-b/station-assignments-by-huc.md
- 'Appendix C - Colorado SWSI Workflow Details': appendix-c/colorado-swsi-workflow-details.md
- 'Appendix D - Historical Period Data Issues': appendix-d/historical-period-data-issues.md
- 'Appendix E - Current Water year Data Issues': appendix-e/current-water-year-data-issues.md
- 'Appendix F - Recent Period Data Issues': appendix-f/recent-period-data-issues.md
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  Copyright Open Water Foundation
# ------------------------------------------------
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
google_analytics:
- 'UA-135465513-1'
- auto
# ------------------------------------------------
# Favicon is supposed to automatically be found:
# - in docs/img/favicon.ico
# - is a copy of docs/images/OWF-Logo-Favicon-32x32.ico
# - instead, with Material them, have a different approach (see "theme" below)
# ------------------------------------------------
# Don't enable the repo URL because irritating edit icons are shown when editing really isn't allowed
#repo_url:  https://github.com/OpenWaterFoundation/owf-models-swsi
# ------------------------------------------------
site_author:  Open Water Foundation
site_description:  Surface Water Supply Index
# ------------------------------------------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: material
  favicon: 'images/favicon.ico'
# ------------------------------------------------
# The following controls how URLs are created
# - As of MkDocs 1.0 the default is true meaning URLs to a page ABC is ABC/ rather than something/ABC.html.
# - see:  https://www.mkdocs.org/user-guide/configuration/#use_directory_urls
# use_directory_urls: true
# ------------------------------------------------
